### ISSUE TITLE
Can't enable Sverchok 1.0.0 in Blender with Python 3.10 (3.1.0 - 3.2.1)

### ISSUE THREAD

**Issue by romanvolodin** [nortikin/sverchok#4600]
## Can't enable Sverchok 1.0.0 in Blender with Python 3.10 (3.1.0 - 3.2.1).
Got an errors when trying to enable the addon after installation:
```python
Traceback (most recent call last):
  File "/NAS/tech/soft/blender/blender-3.2.1-linux-x64/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/core/__init__.py", line 97, in init_architecture
    import_settings(imported_modules, sv_name)
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/core/__init__.py", line 78, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "/NAS/tech/soft/blender/blender-3.2.1-linux-x64/3.2/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/settings.py", line 10, in <module>
    from sverchok.core import main_tree_handler  # don't remove this should fix #4229 (temp solution)
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/core/main_tree_handler.py", line 18, in <module>
    from sverchok.utils.tree_structure import Tree, Node
  File "/home/roman/.config/blender/3.2/scripts/addons/sverchok-1_0_0/utils/tree_structure.py", line 11, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/NAS/tech/soft/blender/blender-3.2.1-linux-x64/3.2/python/lib/python3.10/collections/__init__.py)
```
## Why that happens

The Internet says that happens because of changes in Python 3.10.
Same Sverchok version works fine in Blender 3.0.1, which uses Python 3.9.

## How to fix
Replace
```python
from collections import ...
```
with
```python
from collections.abc import ...
```
in the following files:
```
sverchok/utils/meshes.py
sverchok/utils/handle_blender_data.py
sverchok/utils/tree_structure.py
```

Maybe it make sense to use something like:
```python
try:
    from collections.abc import ...
except ImportError:
    from collections import ...
```

**Comment by Durman** [comment]
I guess this version include the fixes - https://github.com/nortikin/sverchok/releases/tag/v1.0.1

**Comment by endeavor9x** [comment]
> I guess this version include the fixes - https://github.com/nortikin/sverchok/releases/tag/v1.0.1
Is there any particular reason why this version is not yet featured in releases?

**Comment by Durman** [comment]
The question is valid because the master is not stable and may include backward incompatible changes of new features.
