### ISSUE TITLE
Prepared archive with Python libraries

### ISSUE THREAD

**Issue by OURLEDS** [nortikin/sverchok#4049]
## The owner either removed the files or restricted access, or there's a typo in the link.

At FAQ https://github.com/nortikin/sverchok/wiki/FAQ 
On the 
"I can't install dependencies on Windows" The link--> Another possibility is to use a prepared archive with Python libraries.  
https://disk.yandex.com/d/GkxlG9udNfWdfw

SHOWS THIS: 
"The owner either removed the files or restricted access, or there's a typo in the link."

## Steps to reproduce

1. GO FAQ
2. Go to "I can't install dependencies on Windows"
3. Click on "archive with Python libraries"
4. See the error.

## Expected result

FILES TO DOWNLOAD AND SOLVING the problem, of WHY I AM THE ONLY ONE without being able to use svershok on BLENDER 2.92. 

## Actual result

Can't use any node, everything red, can't load any file cointaining svershok nodes and funtions. All I get are erros and red blocks:
![imagen](https://user-images.githubusercontent.com/46494097/114900686-070caf00-9e0c-11eb-820a-156ee6f30411.png)

## Sverchok version

Any Svershock version

**Comment by maxim1967** [comment]
Извините забыл обновить инфу:
Скомпилированным набором для Blender 2.91 https://disk.yandex.ru/d/ZX4_jPGMRUvP7Q или для Blender 2.92 https://disk.yandex.ru/d/CRUxCC4RshA3qg просто распакуйте архив в C:\Program Files\Blender Foundation\Blender 2.91\2.91 (или *\2.92)  В данные архивы входят и библиотеки для Sverchok-extra и Sverchok-open3d кроме Pygalmesh для нее нужно еще ставить Визуал C++ 14.0

**Comment by maxim1967** [comment]
Updated the information in the FAQ.

**Comment by OURLEDS** [comment]
Thanks so much. I am having a lot of issues because I don't know how to use python to install missing dependacies. Everytime I use a comand of python meant to be to fix problems my python terminal says wrong syntax
And If I use in the CMD, it does install ony my versions of py on the system, but it does not install it on the Blender path.

**Comment by OURLEDS** [comment]
By the way, amazing your fast reply. You are a awesome contributor.

**Comment by OURLEDS** [comment]
And last but not least, is it possible to have them for Blender 2.79? Is incredibly important. Aparently my next issue for "'NodeSocket' object has no attribute 'socket_id'" is to use Blender 2.79 especifically.

**Comment by maxim1967** [comment]
I'm sorry, but I don't work with Blender 2.79.

**Comment by Durman** [comment]
@OURLEDS Sverchok on Blender 2.79 stage did not have any dependencies because nodes, that use them, was not implemented yet.
