### ISSUE TITLE
Cannot make sverchok (b28 prelease version) work with Blender 2.8

### ISSUE THREAD

**Issue by solub** [nortikin/sverchok#2429]
## Problem statement

Hi,

Whenever I try to check the sverchok environment (b28 prelease version) from the add-ons menu in Blender 2.80 I get an "ImportError":

`cannot import name 'handlers' from 'sverchok.core' ('C:\Users\MyName\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py)`

I tried to install it from the addons installer in Preference or by dropping the extracted zip file directly in the addons_contrib folder, without success.

I'm running windows 10.
Blender version: 2.80 beta 64 bits, today's release (may 31 2019)

I looked for similar issues but none of the solutions worked. 

## Steps to reproduce

1. 
2. 
3. 

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/2326

**Comment by zeffii** [comment]
let us know if the issue i linked solved your installation issue @solub   ,

**Comment by zeffii** [comment]
OK,  i closed this because there's no code that I could change to make that suddenly work for you.

**Comment by KenHoffmeyer** [comment]
Same issue as the OP, and I have some more info so it may be worth reopening.  I had tried the existing release version of the addon and realized it wasn't updated for 2.8 yet.  Then I followed the directions 
in #2326 and got this error:

Traceback (most recent call last):
  File "C:\blender\2.80\scripts\modules\addon_utils.py", line 352, in enable
    mod.__time__ = os.path.getmtime(mod.__file__)
  File "C:\blender\2.80\python\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\blender\\2.80\\scripts\\addons_contrib\\sverchok-master\\__init__.py'

Since it was looking for a sverchok-master folder, I renamed my folder to sverchok-master, hit Refresh in the Addons Prefs, then tried to enable Sverchok.  It found the file it was looking for, but then I got this instead:

Traceback (most recent call last):
  File "C:\blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\blender\2.80\scripts\addons_contrib\sverchok-master\__init__.py", line 77, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 99, in init_architecture
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 80, in import_settings
  File "C:\blender\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\blender\2.80\scripts\addons_contrib\sverchok-master\settings.py", line 8, in <module>
    from sverchok.core import handlers
ImportError: cannot import name 'handlers' from 'sverchok.core' (C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py)

I'm wondering if this has something to do with trying the old version first and it somehow dirties up Blenders addon info.

**Comment by zeffii** [comment]
sorry you had to experience this. hopefully plain-sailing from this point onwards. @KenHoffmeyer

**Comment by zeffii** [comment]
(and i don't want to add code that automates what you just did, because.. well.. "there be dragons" )

**Comment by KenHoffmeyer** [comment]
Not a problem.  Once I got it working, I just wanted it to be documented somewhere so others who run into it can work their way through it.  Not sure about dragons, but there's certainly goblins in my machine.
