### ISSUE TITLE
Scripted node lite : ui curves manual is this working with blender 2.82.6

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2769]
I think this is not working with blender 2.82.6
![image](https://user-images.githubusercontent.com/49908008/71452052-cd301900-2780-11ea-8f2a-82954f37697d.png)

**Comment by Durman** [comment]
```Python
>>> bpy.data.materials[1].node_tree.nodes[2].mapping.curves[3].evaluate
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'CurveMap' object has no attribute 'evaluate'
```
It related with API changes of Blender 2.82. In 2.81 it works. It looks like that for 2.82 we can implement better solution with new coming widgets.
https://developer.blender.org/rBba1e9ae4733a

For 2.82 you can use `F curve in` node instead.
![2019-12-26_08-25-36](https://user-images.githubusercontent.com/28003269/71457860-7abf1e80-27b9-11ea-9d8e-5a4b63de7aa1.png)

**Comment by zeffii** [comment]
maybe also
```python

layout.prop(props, "use_custom_profile")
--
if props.use_custom_profile:
    tool_settings = context.tool_settings
    layout.template_curveprofile(tool_settings, "custom_bevel_profile_preset")
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/76687012-6c4a0b80-6620-11ea-91fe-8d4ab34f2962.png)
https://github.com/nortikin/sverchok/pull/2971
