### ISSUE TITLE
2.8 topics

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1783]
This issue hopes to collect major Blender Python API changes that may or may not affect sverchok.

see: https://wiki.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts

- 2.8 will drop the `bpy.utils.register_module` function, this doesn't affect us much..or maybe at all.
- [x] 2.8 will enforce a naming convention for `bl_idname` of operators/menus/headers/panels and uiLists.
   - We will need to update these, and could already start gradually migrating over to make the final 2.8 step easier. Big task but very boring/scriptable.
- [ ] 2.8 the event handlers we rely on are gone, but I suspect appropriate alternatives will be supplied or we really have to focus purely on `update=updateNode` to traverse the graph.
    - **NEW** bpy.app.handlers.depsgraph_update_pre/post  ( https://developer.blender.org/rB4b06d0bf51c38c4358c07823358589ca1cdc6f47  )
- [ ] 2.8 things we rely on for any `bgl` drawing ( stethoscope, vdmk2, indexviewer ) are all impacted. 
- [x] 2.8 no longer allows arbitrary assignments to `bpy.types`  (small task- done!)
- [x] 2.8 registering classes, node class references not automatically located in `bpy.types` (big task- done!)

#### Regisering classes

A suggestion on that page gives: ( i like this.. we can use this a lot..can even use our own version of this for pre 2.8 sverchok ..)
```python
classes = (
    FooClass,
    BarClass,
    BazClass,
)
register, unregister = bpy.utils.register_classes_factory(classes)  # not yet (or ever?) in 2.79
```
this will work for most node files, i'm not immediately aware that any nodes register scene variables directly in `register` (but there might be one or two)

#### bl_idname

...

#### BGL

a few `bgl` functions that we use are now dropped from `bgl`. I'm not sure how large the impact on the drawing code is. Good opportunity to write a new Viewer node.
see : https://gamedev.stackexchange.com/questions/34108/opengl-vbo-or-glbegin-glend

**Comment by zeffii** [comment]
i might not be available to do any of this.

**Comment by nortikin** [comment]
why?

**Comment by zeffii** [comment]
external pressures :/

**Comment by nortikin** [comment]
what does mean ```will enforce a naming convention for bl_idname of operators/menus/headers/panels and uiLists.``` ?
what exact changes in bl_idname we need to do?

**Comment by zeffii** [comment]
not sure from what I understand
- menus will become `SV_MT_SomeMenu`
- operators will become `SV_OT_SomeOperator`.
- panels..  `SV_PT_SomePanel`.  etc

( not a massive issue... but if we don't follow the new convention it will be lifeless )

Not sure _if_ or _how_ Node subclasses will be treated. Lukily we already prefix most of those anyway :)

**Comment by zeffii** [comment]
we can definitely already migrate menus/operators and panel to be consistent with the regex Blender will use:
```python
pattern = `[A-Z][A-Z0-9_]*_MT_[A-Za-z0-9_]+`
```

**Comment by enzyme69** [comment]
​If Sverchok does not work with Blender 2.8, I will stick with 2.79 for a
while.

**Comment by zeffii** [comment]
2.8 doesn't draw the nodeview properly on my crappy Lenovo laptop. I've been told to wait about 6 months before taking 2.8 serious enough to work on GL code.

**Comment by zeffii** [comment]
if we keep up to date with `2.79 nightlies` builder bot builds the final step-over to 2.8 will be less of a jump.

**Comment by DolphinDream** [comment]
External pressure :) Like a comet set on direct path with Earth ? :)

**Comment by zeffii** [comment]
> Like a comet set on direct path with Earth ?

comets. the universe's answer to ignorance :)

**Comment by nortikin** [comment]
Bl_idname. What to do? Not clear to me. Where to read?

**Comment by zeffii** [comment]
The link at the top @nortikin  is all the information we've been given. But .. for example
```python
# SvMoveSocketOpExp(Operator, MonadOpCommon)
SvMoveSocketOpExp -> SV_OT_MoveSocketOpExp
```

**Comment by zeffii** [comment]
I am not sure if we need to manually pass 
```python
bl_idname = "node.sverchok_move_socket_exp"
```
it might already default to something else if we don't.
```python
# bl_idname = "ops.SV_OT_MoveSocketOpExp"
```

will need to experiment.

**Comment by Theverat** [comment]
Oops, I didn't know github would create a notice here if I linked this issue from my repository, sorry.

Since I'm here already:
If a class does not define a `bl_idname`, the class name is used as `bl_idname`.

**Comment by Durman** [comment]
Changing in user interface:

[![Alt text](https://img.youtube.com/vi/_WBqTeLcsxU/0.jpg)](https://youtu.be/_WBqTeLcsxU "Single Column Layout - Blender 2.8 Code Quest")

**Comment by enzyme69** [comment]
I am very curious on how SV can just work in 2.8, maybe there will be some
changes.

**Comment by nortikin** [comment]
```bash
 File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/__init__.py", line 77, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/core/__init__.py", line 99, in init_architecture
    import_settings(imported_modules, sv_name)
  File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/core/__init__.py", line 80, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "/home/ololo/Downloads/INSTALL/blender-2.80-35efa1d3d33-linux-glibc219-x86_64/2.80/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/settings.py", line 8, in <module>
    from sverchok.core import handlers
  File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/core/handlers.py", line 10, in <module>
    from sverchok.ui import (
  File "/home/ololo/.config/blender/2.80/scripts/addons/sverchok/ui/viewer_draw_mk2.py", line 36, in <module>
    from bgl import (
ImportError: cannot import name 'glBegin'
```

**Comment by nortikin** [comment]
BGL go crazy

**Comment by Durman** [comment]
Some more news about Blender 2.8 UI:

https://developer.blender.org/T55386
https://developer.blender.org/T55039
https://developer.blender.org/T55407

**Comment by Durman** [comment]
New node editor is coming:

[![Alt text](https://img.youtube.com/vi/HQi2BqlQtnI/0.jpg)](https://youtu.be/HQi2BqlQtnI "EVERYTHING NODES 🎆 - Blender 2.8 Code Quest")

![2018-06-23_22-15-46](https://user-images.githubusercontent.com/28003269/41812389-08b471d8-7733-11e8-9893-853fc1f1e9b6.png)

![2018-06-23_22-08-30](https://user-images.githubusercontent.com/28003269/41812323-fc8ee628-7731-11e8-8b77-b5f648cfa77c.png)

**Comment by portnov** [comment]
2.8 is already alpha.
https://code.blender.org/2018/06/beyond-the-code-quest/
What is our status?

**Comment by Kosvor2** [comment]
Sverchok can be forced to "work" on 2.8. But without all nodes what use BGL, and nodetree updates only on frame change. Also no way to link new objects to scene. Some icons missing. Here testing branch: https://github.com/nortikin/sverchok/commits/Blender-2.8-testing

**Comment by Durman** [comment]
I heard on `Blender Developers` channel that it is too early to fix addons for Blender 2.8 if you don't want to make the work twice becouse API still is developing and can have changes.

**Comment by portnov** [comment]
Yes, I received the same from them. It is okay... ish... The only thing I am worrying about is that there might be too small gap between "python api stabilization" and "blender release" dates for us to update sverchok.

**Comment by zeffii** [comment]
i think it's perfectly acceptable for a non trivial add-on (like Sverchok) to take some time to update. Once the scripting interface is ready for the bgl replacement.

i'm not going to spend time doing this, i wish others didn't either. ( i already did tests early on :  https://github.com/nortikin/sverchok/tree/b28_test    )

**Comment by nortikin** [comment]
https://developer.blender.org/T56644

**Comment by nortikin** [comment]
https://devtalk.blender.org/t/everything-nodes-with-sverchok/2029 also they say it is better place.

**Comment by zeffii** [comment]
bgl now exists again in 2.8 nightly builds, but glBegin and _End are no longer supported
```python
ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)
```
seems like we must now construct proper VBO. i'll dig into this. :)

**Comment by Kosvor2** [comment]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Draw_API#Examples

**Comment by zeffii** [comment]
looks like fun :)

**Comment by nortikin** [comment]
https://github.com/JacquesLucke/animation_nodes/commits/blender2.8

**Comment by nortikin** [comment]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons
from this:
```2.7x:
class MyOperator(Operator):
    value = IntProperty()
2.8x:
class MyOperator(Operator):
    value: IntProperty()
```
and
```
   [A-Z][A-Z0-9_]*_MT_[A-Za-z0-9_]+
The separator for each class is listed below:
    Header -> _HT_
    Menu -> _MT_
    Operator -> _OT_
    Panel -> _PT_
    UIList -> _UL_
Valid Examples:
    OBJECT_OT_fancy_tool
    SOME_HEADER_HT_my_header
    PANEL123_PT_myPanel (lower case is preferred but mixed case is supported).
```
```
Access (bpy.types)
Classes registered by addons are no longer available in bpy.types. Instead addons can import their own modules and access the classes directly. 
```
Also not register_module, but register_class
```
classes = (
    FooClass,
    BarClass,
    BazClass,
)
register, unregister = bpy.utils.register_classes_factory(classes)
```

**Comment by zeffii** [comment]
`value: IntProperty()`  lol :/

**Comment by zeffii** [comment]
```
__annotations__ = {}
__annotations__["some_property"] = IntProperty(....)
```

**Comment by nortikin** [comment]
well, if we acess own class, will it looks like:
```python
sverchok.trees['__name__'].datasteps[3]=np.array([.....])
```
?

**Comment by zeffii** [comment]
not sure.. but am tempted to start the port very soon. (and no backward compatibility... time for a fresh start? ) keep it very basic at the start.. only very few nodes.

**Comment by nortikin** [comment]
trying to call self for addon radiola.py 2.8
But it is no module 'radiola'
so i donno how to call sverchok from sverchok before register sverchok if i need to register it.

**Comment by nortikin** [comment]
File "//\blender\radiola_2.8.blend\radiola.py", line 85, in draw
AttributeError: module 'radiola' has no attribute 'radiola_clear'
```python
if __name__ == '__main__':
    register()
```

**Comment by zeffii** [comment]
i'm starting the 2.8 port now.  i need distraction or something :)

**Comment by nortikin** [comment]
that is a question... How AN deal?

**Comment by nortikin** [comment]
https://github.com/JacquesLucke/animation_nodes/commit/9ded1d79ce8e9af3b1f333d4e9fd99ebc07b8575#diff-17d098a4c960e0c84587dbe1ec09300aR75
https://github.com/JacquesLucke/animation_nodes/commit/86072a66fdfc88ee3168b0d6a58e55a745f8710b

**Comment by nortikin** [comment]
https://devtalk.blender.org/t/custom-node-trees/1614

**Comment by nortikin** [comment]
```python
import bpy
from bpy.types import NodeTree, Node, NodeSocket

# Implementation of custom nodes from Python


# Derived from the NodeTree base type, similar to Menu, Operator, Panel, etc.
class MyCustomTree(NodeTree):
    # Description string
    '''A custom node tree type that will show up in the node editor header'''
    # Optional identifier string. If not explicitly defined, the python class name is used.
    bl_idname = 'CustomTreeType'
    # Label for nice name display
    bl_label = "Custom Node Tree"
    # Icon identifier
    bl_icon = 'NODETREE'


# Custom socket type
class MyCustomSocket(NodeSocket):
    # Description string
    '''Custom node socket type'''
    # Optional identifier string. If not explicitly defined, the python class name is used.
    bl_idname = 'CustomSocketType'
    # Label for nice name display
    bl_label = "Custom Node Socket"

    # Enum items list
    my_items = (
        ('DOWN', "Down", "Where your feet are"),
        ('UP', "Up", "Where your head should be"),
        ('LEFT', "Left", "Not right"),
        ('RIGHT', "Right", "Not left")
    )

    my_enum_prop = bpy.props.EnumProperty(name="Direction", description="Just an example", items=my_items, default='UP')

    # Optional function for drawing the socket input value
    def draw(self, context, layout, node, text):
        if self.is_output or self.is_linked:
            layout.label(text)
        else:
            layout.prop(self, "my_enum_prop", text=text)

    # Socket color
    def draw_color(self, context, node):
        return (1.0, 0.4, 0.216, 0.5)


# Mix-in class for all custom nodes in this tree type.
# Defines a poll function to enable instantiation.
class MyCustomTreeNode:
    @classmethod
    def poll(cls, ntree):
        return ntree.bl_idname == 'CustomTreeType'


# Derived from the Node base type.
class MyCustomNode(Node, MyCustomTreeNode):
    # === Basics ===
    # Description string
    '''A custom node'''
    # Optional identifier string. If not explicitly defined, the python class name is used.
    bl_idname = 'CustomNodeType'
    # Label for nice name display
    bl_label = "Custom Node"
    # Icon identifier
    bl_icon = 'SOUND'

    # === Custom Properties ===
    # These work just like custom properties in ID data blocks
    # Extensive information can be found under
    # http://wiki.blender.org/index.php/Doc:2.6/Manual/Extensions/Python/Properties
    my_string_prop = bpy.props.StringProperty()
    my_float_prop = bpy.props.FloatProperty(default=3.1415926)

    # === Optional Functions ===
    # Initialization function, called when a new node is created.
    # This is the most common place to create the sockets for a node, as shown below.
    # NOTE: this is not the same as the standard __init__ function in Python, which is
    #       a purely internal Python method and unknown to the node system!
    def init(self, context):
        self.inputs.new('CustomSocketType', "Hello")
        self.inputs.new('NodeSocketFloat', "World")
        self.inputs.new('NodeSocketVector', "!")

        self.outputs.new('NodeSocketColor', "How")
        self.outputs.new('NodeSocketColor', "are")
        self.outputs.new('NodeSocketFloat', "you")

    # Copy function to initialize a copied node from an existing one.
    def copy(self, node):
        print("Copying from node ", node)

    # Free function to clean up on removal.
    def free(self):
        print("Removing node ", self, ", Goodbye!")

    # Additional buttons displayed on the node.
    def draw_buttons(self, context, layout):
        layout.label("Node settings")
        layout.prop(self, "my_float_prop")

    # Detail buttons in the sidebar.
    # If this function is not defined, the draw_buttons function is used instead
    def draw_buttons_ext(self, context, layout):
        layout.prop(self, "my_float_prop")
        # my_string_prop button will only be visible in the sidebar
        layout.prop(self, "my_string_prop")

    # Optional: custom label
    # Explicit user label overrides this, but here we can define a label dynamically
    def draw_label(self):
        return "I am a custom node"


### Node Categories ###
# Node categories are a python system for automatically
# extending the Add menu, toolbar panels and search operator.
# For more examples see release/scripts/startup/nodeitems_builtins.py

import nodeitems_utils
from nodeitems_utils import NodeCategory, NodeItem

# our own base class with an appropriate poll function,
# so the categories only show up in our own tree type
class MyNodeCategory(NodeCategory):
    @classmethod
    def poll(cls, context):
        return context.space_data.tree_type == 'CustomTreeType'


# all categories in a list
node_categories = [
    # identifier, label, items list
    MyNodeCategory('SOMENODES', "Some Nodes", items=[
        # our basic node
        NodeItem("CustomNodeType"),
    ]),
    MyNodeCategory('OTHERNODES', "Other Nodes", items=[
        # the node item can have additional settings,
        # which are applied to new nodes
        # NB: settings values are stored as string expressions,
        # for this reason they should be converted to strings using repr()
        NodeItem("CustomNodeType", label="Node A", settings={
            "my_string_prop": repr("Lorem ipsum dolor sit amet"),
            "my_float_prop": repr(1.0),
        }),
        NodeItem("CustomNodeType", label="Node B", settings={
            "my_string_prop": repr("consectetur adipisicing elit"),
            "my_float_prop": repr(2.0),
        }),
    ]),
]

classes = (
    MyCustomTree,
    MyCustomSocket,
    MyCustomNode,
)

def register():
    from bpy.utils import register_class
    for cls in classes:
        register_class(cls)

    nodeitems_utils.register_node_categories('CUSTOM_NODES', node_categories)


def unregister():
    nodeitems_utils.unregister_node_categories('CUSTOM_NODES')

    from bpy.utils import unregister_class
    for cls in reversed(classes):
        unregister_class(cls)


if __name__ == "__main__":
    register()

```

**Comment by zeffii** [comment]
it's already partially working, it was a lot of work...  adding the viewers back today (new versions of existing viewer/objects nodes)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/47952407-19ae0900-df6f-11e8-9591-cecc74df5603.png)

**Comment by zeffii** [comment]
current status is here in this pullrequest: https://github.com/nortikin/sverchok/pull/2299

**Comment by Durman** [comment]
[![Alt text](https://img.youtube.com/vi/j1quOfAxW6w/0.jpg)](https://youtu.be/j1quOfAxW6w "Blender 2.8 Screencast Addon : GPU Shader Python API")

**Comment by Durman** [comment]
Can be useful.
[![Alt text](https://img.youtube.com/vi/ylggq0eFN5A/0.jpg)](https://youtu.be/ylggq0eFN5A "Python tutorial in which I show how I use the Python API and the Gpu module to draw into the 3D view")

**Comment by zeffii** [comment]
closing this because i dont want to have todolists in two places for the same project
