### ISSUE TITLE
Circular import error in 4.2 Nightly

### ISSUE THREAD

**Issue by kursad-k** [nortikin/sverchok#5122]
It seems like neither the latest nightly (5/19/24) nor the bgl replacement branch seems to work in Blender 4.2, throwing a peculiar error called "circular import"  when the addon enabled.

```
\scripts\addons\sverchok-master\__init__.py", line 99, in import_sverchok
    import sverchok.core as core
ImportError: Add-on not loaded: "sverchok-master", cause: cannot import name 'core' from partially initialized module 'sverchok-master' (most likely due to a circular import)
```

Thanks

**Comment by satabol** [comment]
If you did not find solution can you do screenshot of console? Or if you work on Mac then screen of Error ? (Extent windows with error message to see all error)

**Comment by kursad-k** [comment]
@satabol 

```
addon_utils.disable: sverchok-master not loaded
Traceback (most recent call last):
  File "C:\BLENDER42\4.2\scripts\modules\addon_utils.py", line 381, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BLENDER42\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\sverchok-master\__init__.py", line 114, in <module>
    imported_modules, node_modules, core = import_sverchok()
                                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\sverchok-master\__init__.py", line 99, in import_sverchok
    import sverchok.core as core
ImportError: Add-on not loaded: "sverchok-master", cause: cannot import name 'core' from partially initialized module 'sverchok-master' (most likely due to a circular import) (C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\sverchok-master\__init__.py)


```

**Comment by satabol** [comment]
Hi @kursad-k 
I got that error with Blender 4.2-Alpha today. Now this error raise in Node "Regular Solid": no library "add_mesh_extra_objects" in Blender 4.2-Alpha. So I disable this node if there is no that library. In Blender versions <4.2 all work good.

Can you update Sverchok now and test it in Blender 4.2-Alpha?

**Comment by kursad-k** [comment]
How do you disable the node? I cant enable Sverchok so not sure how I can disable an addon under it.

**Comment by satabol** [comment]
Try this:
![image](https://github.com/nortikin/sverchok/assets/14288520/4c15e9d0-94cf-4360-9bd5-633648cb4dfe)

**Comment by satabol** [comment]
after update code will change. You will not restore something. I think. )))

**Comment by kursad-k** [comment]
Thanks, I did not see the bottom of the comment. Your updates fixes the issue for now.

**Comment by satabol** [comment]
You have to comment only ONE line of code.

**Comment by satabol** [comment]
If all right one can close this Issue ?

**Comment by gerroon** [comment]
@satabol 
I checked chechked the latest version and this current work around does not seem to work. I can get Sverchok to work if I fully comment them out as you recommended before.

```
try:
    from add_mesh_extra_objects.add_mesh_solid import createSolid
except ImportError:
    createSolid = None 

```

**Comment by satabol** [comment]
Hi @gerroon 
Can you do screenshot of error ? I test today build of Blender "blender-4.2.0-alpha+main.ce062f03a33f-windows.amd64-release" and Sverchok starts good in my computer (Windows 11, Sverchok-master)

**Comment by kursad-k** [comment]
I deleted the folder and reinstalled the new master branch, it works now.
