### ISSUE TITLE
Generative Art Node not working in Blender 3.0

### ISSUE THREAD

**Issue by GoldenAdrien** [nortikin/sverchok#4396]
## Problem statement

So basically, after my computer restarted, the generative art node no longer worked, so I tried reinstalling the add-on, but that still didn't work. It fails to load even the example scripts and just says either keyError('sockets') or Error: 'NoneType' object has no attribute 'groups'.

The console log says:

```
6_spirals.xml failed to find a directive in this script: SNLITE Error 1 (see docs for more info)
start --->
<rules max_depth="150">
<rule name="entry">
    <call count="3" transforms="rz 120" rule="R1"/>
    <call count="3" transforms="rz 120" rule="R2"/>
</rule>
<rule name="R1">
    <call transforms="tx 2.6 rx 3.14 rz 12 ry 6 sa 0.97" rule="R1"/>
    <instance  transforms="sa 2.6" shape="box"/>
</rule>
<rule name="R2">
    <call transforms="tx -2.6 rz 12 ry 6 sa 0.97" rule="R2"/>
    <instance transforms="sx 2.6" shape="box"/>
</rule>
</rules>
<--- end
```

this was done in the release version of Sverchok-1.0.0

**Comment by GoldenAdrien** [comment]
actually I am stupid, I used the script node lite instead of the generative art node, closing this now and sorry for wasting time.
