### ISSUE TITLE
Quick search not working in blender 4.3

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#5176]
Hi mates!

Only macros appear on the search menu 

```
11:51:53.724 [ERROR] sverchok ui/sv_extra_search.py:66 - Nodetype "<class 'sverchok.nodes.generator.line_mk4.SvLineNodeMK4'>": ensure_valid_show_string() threw an exception:
 'Struct' object has no attribute 'docstring'
11:51:53.725 [ERROR] sverchok ui/sv_extra_search.py:66 - Nodetype "<class 'sverchok.nodes.generator.segment.SvSegmentGenerator'>": ensure_valid_show_string() threw an exception:....
```
