### ISSUE TITLE
Failed to install on Blender 3.1.1 Import Error cannot import name 'main_tree_handler' from 'sverchok.core' 

### ISSUE THREAD

**Issue by fairwelljack** [nortikin/sverchok#4428]
Hi,

I've been trying to enable this addon in blender but this error shows up. please help me if someone knows it.

Thank you!

Report: Error 
Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable mod = import__(module_name) File "CAUsers\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sverchok-mastek_init_.py", line 76, in <module> imported_ modules = init_architecture(name_, utils_modules, ui_modules) File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sverchok-1_0_0\core\init_.py", line 97, in init_architecture File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sverchok-1_0_0\core\_init_.py", line 78, in import_settings File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\importlibUnit_.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "CAUsers\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sverchok-master\settings.py", line 10, in <module> from sverchok.core import main_tree_handler # don't remove this should fix #4229 (temp solution) ImportError: cannot import name 'main_tree_handler' from 'sverchok.core' (C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\sverchok-1_0_0\core\init__.py)

**Comment by fairwelljack** [comment]
I think it must be a problem for blender version higher than 3.0.
Addon was successfully installed on blender 2.93

**Comment by zeffii** [comment]
it works fine in 3.1 and to my knowledge also 3.2 - but you might have to:
- remove the sverchok folders from wherever that version of Blender is looking for them
- install from the [master zip](https://github.com/nortikin/sverchok/archive/refs/heads/master.zip)., rather than the "stable zip"

**Comment by fairwelljack** [comment]
> it works fine in 3.1 and to my knowledge also 3.2 - but you might have to:
> 
> * remove the sverchok folders from wherever that version of Blender is looking for them
> * install from the [master zip](https://github.com/nortikin/sverchok/archive/refs/heads/master.zip)., rather than the "stable zip"

Thank you! that totally worked!

**Comment by Durman** [comment]
Sverchok 1.0 does not work with Blender 3.1 and higher.
